# Generated by Django 5.0 on 2025-12-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_student_course_student_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BBA', 'BBA'), ('MBA', 'MBA'), ('CSE', 'CSE'), ('THM', 'THM')], default='BBA', help_text='Course (BBA, MBA, CSE, THM)', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='intake',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('9th', '9th'), ('10th', '10th'), ('15th', '15th'), ('16th', '16th'), ('17th', '17th'), ('18th', '18th'), ('19th', '19th'), ('20th', '20th')], default='15th', help_text='Intake number', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], default='1st', help_text='Current semester', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='session',
            field=models.CharField(default='2024-2025', help_text='Academic session (e.g., 2023-2024)', max_length=50),
        ),
    ]
