# Generated by Django 5.0 on 2025-12-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_student_batch_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course'], name='accounts_st_course_dfd7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['intake'], name='accounts_st_intake_d95582_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['semester'], name='accounts_st_semeste_488278_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['session'], name='accounts_st_session_bfc695_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['course', 'intake', 'semester', 'session'], name='accounts_st_course_4e3a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='accounts_st_student_cfc700_idx'),
        ),
    ]
