# Generated by Django 5.0 on 2026-05-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_clear_seeded_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_waiver',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Total fee waiver granted (Tk)', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='intake_batch',
            field=models.CharField(blank=True, db_index=True, help_text='Intake batch label as recorded in source data (e.g. "14th", "17th-SW")', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_tuition_fee',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Monthly tuition fee (Tk)', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, db_index=True, help_text='College roll number (from admission records)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester_fee',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Fee per semester form-fillup (Tk)', max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='total_program_fee',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Total tuition fee for the whole program (Tk)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_date',
            field=models.DateField(blank=True, help_text='Date of admission', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Student date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='intake',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('7th', '7th'), ('8th', '8th'), ('9th', '9th'), ('10th', '10th'), ('11th', '11th'), ('12th', '12th'), ('13th', '13th'), ('14th', '14th'), ('15th', '15th'), ('16th', '16th'), ('17th', '17th'), ('17th-SW', '17th-SW'), ('18th', '18th'), ('19th', '19th'), ('20th', '20th')], default='15th', help_text='Intake number', max_length=10),
        ),
    ]
