# Generated by Django 5.0 on 2026-05-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_student_fee_waiver_student_intake_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COORDINATOR', 'Coordinator'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], default='STUDENT', help_text='User role in the system', max_length=15),
        ),
    ]
