# Generated by Django 5.0 on 2025-12-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_exam_batch_exam_course_exam_intake_and_more'),
        ('payments', '0002_remove_feestructure_batch_feestructure_course_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='batch',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
