# Generated by Django 5.0 on 2025-12-16 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_subject_options_subject_course_code_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exam',
            name='academics_e_intake_6cbc65_idx',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='academics_e_course_c5343d_idx',
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Subject this exam belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(help_text='Exam name (format: Course - Semester - Subject - Type)', max_length=200),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='intake',
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-exam_date', 'subject__name'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('course', 'semester', 'subject', 'exam_type')},
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['subject'], name='academics_e_subject_ff2a4e_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course', 'semester'], name='academics_e_course_80eb15_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course', 'semester', 'subject'], name='academics_e_course_0d6e70_idx'),
        ),
    ]
