# Generated by Django 5.0 on 2025-12-16 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_exam_options_and_more'),
        ('accounts', '0008_student_major_student_major_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the class')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', help_text='Attendance status (Present/Absent)', max_length=10)),
                ('course', models.CharField(help_text='Course code (BBA, MBA, CSE, THM)', max_length=10)),
                ('intake', models.CharField(help_text='Intake number', max_length=10)),
                ('semester', models.CharField(help_text='Semester', max_length=10)),
                ('session', models.CharField(blank=True, help_text='Academic session (e.g., 2023-2024)', max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.student')),
                ('subject', models.ForeignKey(help_text='Subject for which attendance is being recorded', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='academics.subject')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'student__student_id'],
                'indexes': [models.Index(fields=['date'], name='academics_a_date_622e79_idx'), models.Index(fields=['course'], name='academics_a_course_294c9c_idx'), models.Index(fields=['intake'], name='academics_a_intake_4ad2c9_idx'), models.Index(fields=['semester'], name='academics_a_semeste_66cba1_idx'), models.Index(fields=['subject'], name='academics_a_subject_8c6fdb_idx'), models.Index(fields=['student'], name='academics_a_student_b5ab74_idx'), models.Index(fields=['course', 'intake', 'semester', 'subject', 'date'], name='academics_a_course_93e028_idx')],
                'unique_together': {('student', 'subject', 'date')},
            },
        ),
    ]
