# Generated by Django 5.0 on 2025-11-09 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.ForeignKey(help_text='Assigned batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.batch'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(help_text='Link to User account', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
