# Generated by Django 5.0.1 on 2025-11-29 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, help_text="Father's full name", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_phone',
            field=models.CharField(blank=True, help_text="Father's contact number", max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_yearly_income',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Guardian's yearly income", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hsc_4th_subject',
            field=models.CharField(blank=True, help_text='HSC 4th subject', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hsc_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='HSC CGPA', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hsc_college',
            field=models.CharField(blank=True, help_text='HSC college name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hsc_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='HSC GPA', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hsc_group',
            field=models.CharField(blank=True, help_text='HSC group (Science, Commerce, Arts)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hsc_passing_year',
            field=models.PositiveIntegerField(blank=True, help_text='HSC passing year', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, help_text="Mother's full name", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_phone',
            field=models.CharField(blank=True, help_text="Mother's contact number", max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='student',
            name='other_info',
            field=models.TextField(blank=True, help_text='Other information from admission form', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_district',
            field=models.CharField(blank=True, help_text='Permanent address - district', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_division',
            field=models.CharField(blank=True, help_text='Permanent address - division', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_house_no',
            field=models.CharField(blank=True, help_text='Permanent address - house number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_police_station',
            field=models.CharField(blank=True, help_text='Permanent address - police station', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_post_office',
            field=models.CharField(blank=True, help_text='Permanent address - post office', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='permanent_road_vill',
            field=models.CharField(blank=True, help_text='Permanent address - road or village', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_district',
            field=models.CharField(blank=True, help_text='Present address - district', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_division',
            field=models.CharField(blank=True, help_text='Present address - division', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_house_no',
            field=models.CharField(blank=True, help_text='Present address - house number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_police_station',
            field=models.CharField(blank=True, help_text='Present address - police station', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_post_office',
            field=models.CharField(blank=True, help_text='Present address - post office', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='present_road_vill',
            field=models.CharField(blank=True, help_text='Present address - road or village', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], help_text='Current semester', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='session',
            field=models.CharField(blank=True, help_text='Academic session (e.g., 2023-2024)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_4th_subject',
            field=models.CharField(blank=True, help_text='SSC 4th subject', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='SSC CGPA', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_gpa',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='SSC GPA', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_group',
            field=models.CharField(blank=True, help_text='SSC group (Science, Commerce, Arts)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_passing_year',
            field=models.PositiveIntegerField(blank=True, help_text='SSC passing year', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_school',
            field=models.CharField(blank=True, help_text='SSC school name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_address',
            field=models.TextField(blank=True, help_text='Permanent residential address', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='present_address',
            field=models.TextField(blank=True, help_text='Current residential address', null=True),
        ),
    ]
