# Generated by Django 5.0.1 on 2025-12-06 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_father_name_student_father_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='hsc_cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ssc_cgpa',
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, help_text="Guardian's full name", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_phone',
            field=models.CharField(blank=True, help_text="Guardian's contact number", max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
