# Generated by Django 5.0 on 2025-12-14 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_student_hsc_cgpa_remove_student_ssc_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('BBA', 'BBA'), ('MBA', 'MBA'), ('CSE', 'CSE'), ('THM', 'THM')], help_text='Course (BBA, MBA, CSE, THM)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of the student', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_occupation',
            field=models.CharField(blank=True, help_text="Guardian's occupation", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='hsc_board',
            field=models.CharField(blank=True, choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong'), ('rajshahi', 'Rajshahi'), ('comilla', 'Comilla'), ('jessore', 'Jessore'), ('sylhet', 'Sylhet'), ('dinajpur', 'Dinajpur'), ('barishal', 'Barishal'), ('mymensingh', 'Mymensingh'), ('technical', 'Technical'), ('madrasah', 'Madrasah')], help_text='HSC Board', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='intake',
            field=models.CharField(blank=True, choices=[('1st', '1st'), ('2nd', '2nd'), ('9th', '9th'), ('10th', '10th'), ('15th', '15th'), ('16th', '16th'), ('17th', '17th'), ('18th', '18th'), ('19th', '19th'), ('20th', '20th')], help_text='Intake number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='national_id_number',
            field=models.CharField(blank=True, help_text='National ID number (optional)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='national_university_id',
            field=models.CharField(blank=True, help_text='National University ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Registration number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_board',
            field=models.CharField(blank=True, choices=[('dhaka', 'Dhaka'), ('chittagong', 'Chittagong'), ('rajshahi', 'Rajshahi'), ('comilla', 'Comilla'), ('jessore', 'Jessore'), ('sylhet', 'Sylhet'), ('dinajpur', 'Dinajpur'), ('barishal', 'Barishal'), ('mymensingh', 'Mymensingh'), ('technical', 'Technical'), ('madrasah', 'Madrasah')], help_text='SSC Board', max_length=20, null=True),
        ),
    ]
