# Generated by Django 5.0 on 2025-12-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_subject_options_subject_course_code_and_more'),
        ('accounts', '0007_student_accounts_st_course_dfd7cc_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(blank=True, help_text='Selected major (for BBA/MBA students in 7th+ semester)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.majorminoroption'),
        ),
        migrations.AddField(
            model_name='student',
            name='major_locked',
            field=models.BooleanField(default=False, help_text='Whether the major selection is locked (cannot be changed)'),
        ),
    ]
