# Generated by Django 5.0 on 2025-11-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exam name', max_length=200)),
                ('exam_type', models.CharField(choices=[('midterm', 'Mid Term'), ('final', 'Final Exam'), ('ssc', 'SSC Exam'), ('hsc', 'HSC Exam'), ('monthly', 'Monthly Test')], help_text='Type of examination', max_length=20)),
                ('exam_date', models.DateField(help_text='Exam date')),
                ('total_marks', models.PositiveIntegerField(default=100, help_text='Total marks for this exam')),
                ('description', models.TextField(blank=True, help_text='Exam description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, help_text='Marks obtained by student', max_digits=5)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'ordering': ['-exam__exam_date', 'student'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Subject name (e.g., Mathematics, Physics)', max_length=200)),
                ('code', models.CharField(help_text='Unique subject code (e.g., MATH101)', max_length=20, unique=True)),
                ('total_marks', models.PositiveIntegerField(default=100, help_text='Total marks for this subject')),
                ('description', models.TextField(blank=True, help_text='Subject description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['name'],
            },
        ),
    ]
