# Generated by Django 5.0 on 2025-12-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_exam_batch_exam_course_exam_intake_and_more'),
        ('accounts', '0007_student_accounts_st_course_dfd7cc_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course'], name='academics_e_course_13035c_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['intake'], name='academics_e_intake_6cbc65_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['semester'], name='academics_e_semeste_4f1259_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['session'], name='academics_e_session_58c569_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['exam_date'], name='academics_e_exam_da_abf0c8_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course', 'intake', 'semester', 'session'], name='academics_e_course_3b8cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student'], name='academics_r_student_563273_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['exam'], name='academics_r_exam_id_e63a27_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['subject'], name='academics_r_subject_8a93f9_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', 'exam'], name='academics_r_student_27848e_idx'),
        ),
    ]
