# Generated by Django 5.0 on 2025-12-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_exam_academics_e_course_13035c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exam',
            name='academics_e_session_58c569_idx',
        ),
        migrations.RemoveIndex(
            model_name='exam',
            name='academics_e_course_3b8cc6_idx',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='session',
        ),
        migrations.AddField(
            model_name='result',
            name='teacher_comment',
            field=models.TextField(blank=True, help_text='Teacher comment for this result', null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('incourse_1st', '1st Incourse'), ('incourse_2nd', '2nd Incourse'), ('final', 'Final Exam')], help_text='Type of examination', max_length=20),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['course', 'intake', 'semester'], name='academics_e_course_c5343d_idx'),
        ),
    ]
