# Generated by Django 5.0 on 2025-12-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_update_exam_types'),
        ('students', '0002_remove_enrollment_batch_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['course_code', 'semester', 'code'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AddField(
            model_name='subject',
            name='course_code',
            field=models.CharField(choices=[('BBA', 'BBA'), ('MBA', 'MBA'), ('CSE', 'CSE'), ('THM', 'THM')], default='BBA', help_text='Course code (BBA, MBA, CSE, THM)', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='credit_hours',
            field=models.DecimalField(decimal_places=1, default=3.0, help_text='Credit hours for this subject', max_digits=3),
        ),
        migrations.AddField(
            model_name='subject',
            name='has_practical',
            field=models.BooleanField(default=False, help_text='Whether this subject has a practical component'),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this subject currently offered?'),
        ),
        migrations.AddField(
            model_name='subject',
            name='practical_marks',
            field=models.PositiveIntegerField(default=0, help_text='Marks allocated for practical (if any)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('1st', '1st'), ('2nd', '2nd'), ('3rd', '3rd'), ('4th', '4th'), ('5th', '5th'), ('6th', '6th'), ('7th', '7th'), ('8th', '8th')], default='1st', help_text='Semester this subject belongs to', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('core', 'Core/Compulsory'), ('major', 'Major'), ('elective', 'Elective'), ('lab', 'Laboratory'), ('project', 'Project/Internship'), ('viva', 'Viva Voce')], default='core', help_text='Type of subject', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='Unique subject code (e.g., 510101)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Associated course', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.course'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Subject name (e.g., Introduction to Business)', max_length=200),
        ),
        migrations.CreateModel(
            name='MajorMinorOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('BBA', 'BBA'), ('MBA', 'MBA')], help_text='Course this major belongs to', max_length=10)),
                ('name', models.CharField(help_text='Major name (e.g., Marketing, Finance & Banking)', max_length=100)),
                ('code', models.CharField(help_text='Unique code for this major (e.g., BBA_MKT, MBA_FIN)', max_length=20, unique=True)),
                ('option_type', models.CharField(choices=[('major', 'Major')], default='major', help_text='Type of specialization', max_length=10)),
                ('available_from_semester', models.CharField(default='7th', help_text='Semester when students can choose this major', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of this major', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this major currently available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Major Option',
                'verbose_name_plural': 'Major Options',
                'ordering': ['course', 'name'],
                'unique_together': {('course', 'name')},
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='major',
            field=models.ForeignKey(blank=True, help_text='Required major for this subject (if major-specific)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='academics.majorminoroption'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['course_code'], name='academics_s_course__14879f_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['semester'], name='academics_s_semeste_16a9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_type'], name='academics_s_subject_ead729_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['course_code', 'semester'], name='academics_s_course__278e69_idx'),
        ),
    ]
