# Generated by Django 5.0 on 2025-11-09 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='batch',
            field=models.ForeignKey(help_text='Batch taking this exam', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='students.batch'),
        ),
        migrations.AddField(
            model_name='result',
            name='exam',
            field=models.ForeignKey(help_text='Exam', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.exam'),
        ),
        migrations.AddField(
            model_name='result',
            name='student',
            field=models.ForeignKey(help_text='Student', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(help_text='Associated course', on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='students.course'),
        ),
        migrations.AddField(
            model_name='result',
            name='subject',
            field=models.ForeignKey(help_text='Subject', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'exam', 'subject')},
        ),
    ]
