# Generated by Django 5.0 on 2025-12-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_payments_pa_payment_1d6e55_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feestructure',
            name='session',
        ),
        migrations.AddField(
            model_name='payment',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('lab_fee', 'Lab Fee'), ('library_fee', 'Library Fee'), ('fine', 'Fine'), ('semester_fee', 'Semester Fee'), ('tuition_fee', 'Tuition Fee'), ('admission_fee', 'Admission Fee'), ('exam_fee', 'Exam Fee')], help_text='Direct fee type (when not linked to FeeStructure)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_regularity',
            field=models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular')], default='regular', help_text='Payment regularity status (Regular/Irregular)', max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='fee_type',
            field=models.CharField(choices=[('lab_fee', 'Lab Fee'), ('library_fee', 'Library Fee'), ('fine', 'Fine'), ('semester_fee', 'Semester Fee'), ('tuition_fee', 'Tuition Fee'), ('admission_fee', 'Admission Fee'), ('exam_fee', 'Exam Fee')], help_text='Type of fee', max_length=20),
        ),
    ]
