# Generated by Django 5.0 on 2026-05-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_drop_fee_structure_and_safe_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('lab_fee', 'Lab Fee'), ('library_fee', 'Library Fee'), ('fine', 'Fine'), ('semester_fee', 'Semester Fee'), ('tuition_fee', 'Tuition Fee'), ('admission_fee', 'Admission Fee'), ('exam_fee', 'Exam Fee')], help_text='Fee category (free-form label only)', max_length=20, null=True),
        ),
    ]
