# Generated by Django 5.0 on 2026-05-18 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_student_fee_waiver_student_intake_batch_and_more'),
        ('payments', '0007_alter_payment_fee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(blank=True, max_length=10, null=True)),
                ('intake_batch', models.CharField(blank=True, max_length=20, null=True)),
                ('roll_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('application_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('admission_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total_program_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('semester_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('monthly_tuition_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('semester_fee_waived', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('tuition_fee_waived', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total_fees_waived', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('contact_number', models.CharField(blank=True, max_length=30, null=True)),
                ('father_contact', models.CharField(blank=True, max_length=30, null=True)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('income_total', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('pin_no', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admission Record',
                'verbose_name_plural': 'Admission Records',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(blank=True, max_length=255, null=True)),
                ('sheet', models.CharField(blank=True, max_length=100, null=True)),
                ('year_group', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('exam_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('cash_receive', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('cash_expense', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('cash_balance', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Daily Account Entry',
                'verbose_name_plural': 'Daily Account Entries',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(help_text='Program code (e.g. THM, BBA)', max_length=20)),
                ('item', models.CharField(help_text='Fee item name', max_length=100)),
                ('unit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Fee Structure Item',
                'verbose_name_plural': 'Fee Structure Items',
                'ordering': ['program', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SemesterSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(help_text='e.g. "8th Sem"', max_length=20)),
                ('program', models.CharField(blank=True, max_length=10, null=True)),
                ('intake_batch', models.CharField(blank=True, max_length=20, null=True)),
                ('total_program_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('semester_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('monthly_tuition_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('fee_waiver', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('opening_balance', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('semester_total_received', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('closing_balance', models.DecimalField(decimal_places=0, default=0, help_text='Negative = overpaid, positive = dues remaining', max_digits=12)),
                ('cumulative_received_after_semester', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('cumulative_due_after_semester', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('receivable_at_mt_exam', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_receivable_end_of_semester', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('total_payable_at_form_fillup', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('midterm_1_date', models.DateField(blank=True, null=True)),
                ('midterm_1_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('midterm_2_date', models.DateField(blank=True, null=True)),
                ('midterm_2_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('midterm_absent_fine', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('nu_exam_date', models.DateField(blank=True, null=True)),
                ('nu_exam_fee', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('library_deposit', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('library_fine', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('classes_present', models.IntegerField(blank=True, null=True)),
                ('classes_absent', models.IntegerField(blank=True, null=True)),
                ('percent_absent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('absence_fine', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('late_payment_fine_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semester Summary',
                'verbose_name_plural': 'Semester Summaries',
                'ordering': ['student', 'semester'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='late_fine',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Per-slot late payment fine', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='semester',
            field=models.CharField(blank=True, help_text='Semester this payment was recorded against (e.g. "8th Sem")', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fee_type',
            field=models.CharField(blank=True, choices=[('tuition', 'Tuition Fee'), ('application_fee', 'Application Fee'), ('admission_fee', 'Admission Fee'), ('mt_exam_fee', 'Midterm Exam Fee'), ('nu_exam_fee', 'NU Exam Fee'), ('semester_fee', 'Semester Fee'), ('library_deposit', 'Library Deposit'), ('library_fine', 'Library Fine'), ('lab_fee', 'Lab Fee'), ('fine', 'Fine'), ('other', 'Other')], help_text='Fee category (free-form label only)', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['fee_type'], name='payments_pa_fee_typ_571edc_idx'),
        ),
        migrations.AddField(
            model_name='admissionrecord',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='admission_record', to='accounts.student'),
        ),
        migrations.AddIndex(
            model_name='dailyaccount',
            index=models.Index(fields=['year_group'], name='payments_da_year_gr_a5dc81_idx'),
        ),
        migrations.AddIndex(
            model_name='dailyaccount',
            index=models.Index(fields=['date'], name='payments_da_date_db6295_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['program'], name='payments_fe_program_d8251f_idx'),
        ),
        migrations.AddField(
            model_name='semestersummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semester_summaries', to='accounts.student'),
        ),
        migrations.AddIndex(
            model_name='semestersummary',
            index=models.Index(fields=['program', 'intake_batch', 'semester'], name='payments_se_program_fc5dee_idx'),
        ),
        migrations.AddConstraint(
            model_name='semestersummary',
            constraint=models.UniqueConstraint(fields=('student', 'semester'), name='uniq_student_semester_summary'),
        ),
    ]
