# Generated by Django 5.0 on 2026-05-19 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_admissionrecord_dailyaccount_feestructure_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='period_label',
            field=models.CharField(blank=True, help_text='Which period this payment covers, e.g. "May 2026", "Q1 2026"', max_length=40),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, help_text='Expense description'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(blank=True, choices=[('salary', 'Salary'), ('rent', 'Rent'), ('utility', 'Utility'), ('maintenance', 'Maintenance'), ('other', 'Other')], help_text='[Legacy] Free-form type label. Use category instead.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_to',
            field=models.CharField(blank=True, help_text='Payee name', max_length=200),
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('salary', 'Salary'), ('rent', 'Rent'), ('utility', 'Utility'), ('food', 'Food'), ('conveyance', 'Conveyance'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=20)),
                ('default_amount', models.DecimalField(decimal_places=0, default=0, help_text='Suggested amount when creating schedules/expenses', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['kind', 'name'],
                'indexes': [models.Index(fields=['kind'], name='payments_ex_kind_e84706_idx')],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(blank=True, help_text='New: expense category. Falls back to legacy expense_type when null.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='payments.expensecategory'),
        ),
        migrations.CreateModel(
            name='ExpenseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payee', models.CharField(blank=True, help_text='Recipient name (e.g. teacher name, landlord, utility provider)', max_length=200)),
                ('amount_per_period', models.DecimalField(decimal_places=0, max_digits=12)),
                ('frequency', models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('one_time', 'One-time')], default='monthly', max_length=20)),
                ('start_date', models.DateField(help_text='When this obligation begins')),
                ('end_date', models.DateField(blank=True, help_text='Continue until this date (null = ongoing)', null=True)),
                ('day_of_period', models.PositiveSmallIntegerField(blank=True, help_text='Day of month/week when payment is due (optional)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='payments.expensecategory')),
            ],
            options={
                'verbose_name': 'Expense Schedule',
                'verbose_name_plural': 'Expense Schedules',
                'ordering': ['category', 'payee'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Links this outflow to a recurring obligation (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='payments.expenseschedule'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['expense_date'], name='payments_ex_expense_d51e3e_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category', 'expense_date'], name='payments_ex_categor_260ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['schedule', 'period_label'], name='payments_ex_schedul_c679f2_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseschedule',
            index=models.Index(fields=['category', 'is_active'], name='payments_ex_categor_0e018f_idx'),
        ),
        migrations.AddIndex(
            model_name='expenseschedule',
            index=models.Index(fields=['frequency'], name='payments_ex_frequen_9cd9e9_idx'),
        ),
    ]
