# Generated by Django 5.0 on 2025-11-09 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('salary', 'Salary'), ('rent', 'Rent'), ('utility', 'Utility'), ('maintenance', 'Maintenance'), ('other', 'Other')], help_text='Type of expense', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Expense amount', max_digits=10)),
                ('description', models.TextField(help_text='Expense description')),
                ('expense_date', models.DateField(help_text='Date of expense')),
                ('paid_to', models.CharField(help_text='Payee name', max_length=200)),
                ('receipt_file', models.FileField(blank=True, help_text='Receipt file (optional)', null=True, upload_to='expenses/receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='User who recorded this expense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('exam', 'Examination Fee'), ('admission', 'Admission Fee')], help_text='Type of fee', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fee amount', max_digits=10)),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('description', models.TextField(blank=True, help_text='Additional fee details', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(help_text='Associated batch', on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='students.batch')),
            ],
            options={
                'verbose_name': 'Fee Structure',
                'verbose_name_plural': 'Fee Structures',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, help_text='Amount paid', max_digits=10)),
                ('payment_date', models.DateField(help_text='Date of payment')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online Payment')], default='cash', help_text='Payment method used', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction reference ID', max_length=100, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount applied', max_digits=10)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fee_structure', models.ForeignKey(blank=True, help_text='Associated fee structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.feestructure')),
                ('student', models.ForeignKey(help_text='Student making the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
