# Generated by Django 5.0 on 2025-11-09 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Course name (e.g., Higher Secondary Certificate)', max_length=200)),
                ('code', models.CharField(help_text='Unique course code (e.g., HSC, SSC)', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed course description', null=True)),
                ('duration_months', models.PositiveIntegerField(help_text='Course duration in months')),
                ('fee', models.DecimalField(decimal_places=2, help_text='Total course fee', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Is this course currently offered?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Batch name (e.g., HSC 2024)', max_length=100)),
                ('start_date', models.DateField(help_text='Batch start date')),
                ('end_date', models.DateField(help_text='Expected batch end date')),
                ('is_active', models.BooleanField(default=True, help_text='Is this batch currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Associated course', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='students.course')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(editable=False, help_text='Auto-generated employee ID', max_length=20, unique=True)),
                ('subjects', models.TextField(help_text='Subjects taught (comma-separated)')),
                ('qualification', models.CharField(help_text='Educational qualifications', max_length=200)),
                ('joining_date', models.DateField(help_text='Date of joining')),
                ('monthly_salary', models.DecimalField(decimal_places=2, help_text='Monthly salary amount', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Is the teacher currently employed?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Link to User account', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'ordering': ['-joining_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(help_text='Date of enrollment')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', help_text='Current enrollment status', max_length=20)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(help_text='Enrolled batch', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.batch')),
                ('student', models.ForeignKey(help_text='Enrolled student', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrollment_date'],
                'unique_together': {('student', 'batch')},
            },
        ),
    ]
